name: Build
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: docker
    container:
      image: espressif/idf-rust:esp32c3_latest
    steps:
      - run: cargo build --release
