name: Build
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: docker
    container:
      image: espressif/idf-rust:esp32c3_1.77.0.0
    steps:
      - run: cd idf-controller
      - run: cargo build --release
