name: Build
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: docker
    container:
      image: espressif/idf-rust:esp32c3_1.77.0.0
    steps:
      - name: install node
        run: |
          export NODE_VERSION=16.13.0
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          export NVM_DIR=~/.nvm
          . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
          . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
          . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
          export PATH="~/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
          node --version
          npm --version
      - uses: actions/checkout@v4
      - name: build assets
        run: |
          cd idf-controller
          cargo build --release
