name: Build
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4
      - name: build assets
          container:
            image: espressif/idf-rust:esp32c3_1.77.0.0
        run: |
          cd idf-controller
          cargo build --release
