name: Build
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: docker
    container:
      image: cimg/rust:1.45-node
    steps:
      - uses: actions/checkout@v3
      - name: install rust toolchains
        run: rustup toolchain install nightly --component rust-src
      - name: install llvm
        run: |
          SCRIPT_URL=https://gist.github.com/shovon/6151878/raw/62c4f4b5733e772b5a627aebd2b0b32d7cd4ab1e/gistfile1.sh
          mkdir /tmp/llvm-src
          cd /tmp/llvm-src
          curl $SCRIPT_URL | sh
      - name: install ubuntu deps
        run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: install LDproxy
        run: cargo install ldproxy
      - name: build assets
        run: |
          cd idf-controller
          cargo build --release
